config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :static_pages, only: [:index]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    f = Flickr.new
    @list = []

    unless params[:flickr_id].nil? || params[:flickr_id] == ''
      begin
        @list = f.people.getPhotos(user_id: params[:flickr_id])
      rescue
        flash[:notice] = "Not a valid User ID"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<% stylesheet_link_tag 'index' %>
<h1 class="test">Hello World</h1>

<%= flash[:notice] %>

<%= form_with url: static_pages_path, method: :get do |f|%>

  <div><%= f.label :flickr_id, "Enter Your Flicker ID and See your images!" %>
    <%= f.text_field :flickr_id, class: 'id-field' %></div>

  <%= f.submit 'See Now', class: 'id-submit' %>
<% end %>

<div class="grid">
  <% @list.each do |photo| %>
      <%= image_tag("
https://live.staticflickr.com/#{photo.server}/#{photo.id}_#{photo.secret}_w.jpg") %>
  <% end %>
</div>